// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wzonioraytpptnwgoyjn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind6b25pb3JheXRwcHRud2dveWpuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyMDc1OTgsImV4cCI6MjA3MTc4MzU5OH0.waGFv4QRN5CaakTrO17HU6k6kCpOqf4VTUx_cUOIaig";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});